image:
  name: hashicorp/terraform:0.11.11

stages:
  - validate

tffmt:
  stage: validate
  tags:
    - default
  script:
    - terraform fmt -write=false -diff -check

tfvalidate:
  stage: validate
  tags:
    - default
  script:
    - mv main.tf.ci main.tf
    - mv terraform.tfvars.ci terraform.tfvars
    - mkdir -p ~/.ssh/keys
    - touch ~/.ssh/keys/test_test.pem.pub
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@git.fr.clara.net" > "${HOME}/.git-credentials"
    - sed -i -e "s#ssh://git@git\.fr\.clara\.net#https://git.fr.clara.net#g" *.tf
    - terraform init
    - terraform validate
